# k expose statefulset redis-cluster --port 6379 --dry-run=client -oyaml > service.yaml 

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  selector:
    name: redis-cluster
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: gossip              # add this
      port: 16379
      targetPort: 16379